name: StackAttack
version: 0.0.7
author: Simon & Chris
description: An absolute bare-bones web app.
homepage: http://stack.quhfan.de
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
